platform :ios, '8.0'

use_frameworks!

target 'PoporMedia_Example' do
  pod 'PoporMedia', :path => '../'
  pod 'PoporAVPlayer'
  
  target 'PoporMedia_Tests' do
    inherit! :search_paths

    
  end
end
